os: linux
sudo: required
dist: trusty
language: node_js
node_js:
  - "5.0"
  - "4.2"
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.5 mongodb-org-server=3.0.5 mongodb-org-shell=3.0.5 mongodb-org-mongos=3.0.5 mongodb-org-tools=3.0.5
  - sudo apt-get install -y google-chrome-stable
  - sudo curl -s http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip -o /tmp/chromedriver.zip
  - sudo unzip /tmp/chromedriver.zip -d /usr/bin/
  - sudo chmod 755 /usr/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo service mongod status
  - google-chrome --version
  - /usr/bin/chromedriver --version
after_failure:
  - for file in test/artifacts/*; do echo "=== $file"; cat $file; done
